# Generated by Django 6.0.3 on 2026-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('people', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
